name: Rust application build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y cargo rustc libssl-dev pkg-config
    - name: Build application
      run: |
        cargo build
#    - name: Run tests
#      run: |
#        cargo test
